### ISSUE TITLE
Needs Option to Hide Archived Boards

### ISSUE THREAD

**Issue by ronwarner** [dennmart/echo_for_trello#2]
When viewing https://echofortrello.com/boards all boards show up, including archived boards.  Personally I have several archived boards and the number only stands to grow.  Add to that a board for every sprint my dev team at work has done (and archived) and it leaves me with a large mess of boards to look through when writing a new Echo recurring card.  My suggestion would be to hide archived boards by default.  If it seems some people like to create recurring cards on archived boards (I can't think of a reason, but you never know), there could be an option to show those boards.

**Comment by dennmart** [comment]
@ronwarner Sorry this took a bit long to get to - moving to another country tends to take away all your free time for a bit!

I found the issue with this. When I was fetching the user's boards from the Trello API, I was using both the `members` and `open` filter options. The `open` filter by itself should not return closed boards, but when also including the `members` filter, the API would ignore it and return open and closed boards. Not sure if this is an API bug or I just misunderstood how these filters work.

In any case, I agree with you that these boards should not show up at all. I changed it so that Trello only returns open boards, so you should now see significantly less boards on this page. Thanks for the heads up on this!

**Comment by ronwarner** [comment]
Great work, thanks!
